#!/bin/bash
IFS="$"

ls /var/cpanel/users/ > /var/cpanel/users/users
cat /var/cpanel/users/users | while read CPUSER; do
  echo "Now processing ${CPUSER} ..."
  /scripts/pkgacct ${CPUSER}

done

tar cvf /etc/cpbackit/backups.tar  /var/cpanel/users/users /home/cpmove*; rm -rf /var/cpanel/users/users; /etc/cpbackit/ftp; rm -rf /home/cpmove*;
