#! /bin/sh
IFS="$"
HOST=
USER=
PASSWD=
FILE=backups.tar
FOLDER=backups

exec 4>&1
wget -P / ftp://$USER:$PASSWD@$HOST/$FOLDER/$FILE; tar xvf /$FILE; cat /var/cpanel/users/users | while read CPUSER; do echo "Now processing ${CPUSER} ..." /scripts/unpkgacct ${CPUSER};

wait
exit 0

echo "All accounts of this backup file have been restored, thanks for using cPBackIT for your Backup Needs ..."