#!/bin/bash
IFS="$"
echo -e "===============  cPBackIT - Starting Backup Process   =============="
echo -e "===============  Insure the backup process are able to run  =============="
echo -e "-------------------------------------------------------------------------------------------"

/usr/sbin/csf -x; /etc/init.d/csf stop; /etc/init.d/iptables stop

echo -e "=====  cPBackIT - First Backup Stage ( Packing accounts Process )  ====="
echo -e "-------------------------------------------------------------------------------------------"
ls /var/cpanel/users/ > /var/cpanel/users/users
cat /var/cpanel/users/users | while read CPUSER; do
  echo "Now processing ${CPUSER} ..."
  /scripts/pkgacct ${CPUSER}

done
echo -e "===============  cPBackIT - End of the First Backup Stage   =============="
echo -e "-------------------------------------------------------------------------------------------"
echo -e "== cPBackIT - Starting Second Stage ( Packing backups and move to remote server ) =="
echo -e "-------------------------------------------------------------------------------------------"

tar cvf /etc/cpbackit/backups.tar  /var/cpanel/users/users /home/cpmove*; rm -rf /var/cpanel/users/users; /etc/cpbackit/ftp; rm -rf /home/cpmove*;
